# Generated by Django 5.0.2 on 2024-02-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='solutions',
            field=models.ManyToManyField(blank=True, to='achievements.solution'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(blank=True, to='achievements.item'),
        ),
    ]
