# Generated by Django 5.0.2 on 2024-02-23 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImg',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ddns/img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddns.deviceimg')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('log', models.FileField(blank=True, null=True, upload_to='ddns/logs', verbose_name='Log')),
                ('device_uuid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ddns.device')),
            ],
        ),
    ]
