# Generated by Django 5.0.2 on 2024-02-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='device_uuid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='ddns.device'),
        ),
    ]
