# Generated by Django 5.0.4 on 2024-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='verified'),
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
