# Generated by Django 5.0.4 on 2024-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='avatar'),
        ),
    ]
